### ISSUE TITLE
WHAT IS? TypeError: Cannot read properties of null (reading 'checkSecrets') 

### ISSUE THREAD

**Issue by LawlietLL** [alasitsa/mafia-bot#1]
Please, help me

**Comment by LawlietLL** [comment]
```
c:\Discord_Bot_Mafia>node main.js
No secrets.js file found
BotBoi is online!
Started refreshing Mafia Helper application (/) commands.
DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (c:\Discord_Bot_Mafia\node_modules\@discordjs\rest\dist\index.js:667:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (c:\Discord_Bot_Mafia\node_modules\@discordjs\rest\dist\index.js:464:14)
    at async REST.request (c:\Discord_Bot_Mafia\node_modules\@discordjs\rest\dist\index.js:910:22)
    at async c:\Discord_Bot_Mafia\commandhandler.js:93:13 {
  requestBody: {
    files: undefined,
    json: [
      [SlashCommandBuilder],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ]
  },
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v9/applications/1053299489072484382/guilds/984304103268163615/commands'
}
TypeError: Cannot read properties of null (reading 'checkSecrets')
    at Client.<anonymous> (c:\Discord_Bot_Mafia\main.js:130:18)
    at Client.emit (node:events:525:35)
    at MessageCreateAction.handle (c:\Discord_Bot_Mafia\node_modules\discord.js\src\client\actions\MessageCreate.js:26:14)
    at module.exports [as MESSAGE_CREATE] (c:\Discord_Bot_Mafia\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (c:\Discord_Bot_Mafia\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (c:\Discord_Bot_Mafia\node_modules\discord.js\src\client\websocket\WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (c:\Discord_Bot_Mafia\node_modules\discord.js\src\client\websocket\WebSocketShard.js:317:10)
    at callListener (c:\Discord_Bot_Mafia\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (c:\Discord_Bot_Mafia\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
```

**Comment by LawlietLL** [comment]
-
